version: '3'

services:
  database:
    container_name: 'brain-ag-db'
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_ENV}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backendgoline

  api:
    container_name: 'brain-ag'
    build: .
    image: 'node:lts'
    ports:
      - 3333:3333
    volumes:
      - .:/home/api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    networks:
      - backendgoline

networks:
  backendgoline:
    driver: bridge
